version: "3.8"

services:
  foo:
    image: nginx:alpine
    container_name: test_foo
    ports:
      - "8081:80"
    command: /bin/sh -c "echo '<h1>This is Foo</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  bar:
    image: nginx:alpine
    container_name: test_bar
    ports:
      - "8082:80"
    command: /bin/sh -c "echo '<h1>This is Bar</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
