#!/bin/bash

# 1. 检测操作系统并设置路径
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS 鼠须管路径
  RIME_DIR="$HOME/Library/Rime"
  echo "检测到系统: macOS (Squirrel)"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux Fcitx5-Rime 路径
  RIME_DIR="$HOME/.local/share/fcitx5/rime"
  echo "检测到系统: Linux (Fcitx5)"
else
  echo "错误: 不支持的操作系统"
  exit 1
fi

# 2. 检查目录是否存在
if [ ! -d "$RIME_DIR" ]; then
  echo "错误: 找不到 Rime 配置目录 ($RIME_DIR)"
  exit 1
fi

cd "$RIME_DIR" || exit

# 3. 删除用户动态词典数据库 (清理已有的错误词频)
echo "正在清理用户词典数据库 (*.userdb)..."
rm -rf *.userdb/

# 4. 写入或更新补丁配置
# 这里假设你主要使用雾凇拼音 (rime_ice)
# 如果你使用其他方案，可以手动复制此文件并改名
TARGET_CONFIG="rime_ice.custom.yaml"

echo "正在修改配置以禁用自动调频: $TARGET_CONFIG"

# 使用 cat 重写 custom 文件，确保 patch 生效
cat <<EOF >"$TARGET_CONFIG"
# Rime Custom Configuration - Generated by script
patch:
  # 彻底关闭自学习、自动调频和自动造词
  "translator/enable_user_dict": false
  "translator/enable_sentence": false
  "translator/enable_encoder": false
  
  # 如果你使用的是万象词库，通常也建议关闭以下项
  "reverse_lookup_translator/enable_user_dict": false
EOF

# 5. 提示重新部署
echo "------------------------------------------------"
echo "配置完成！"
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "请在 macOS 顶部菜单栏点击输入法图标，选择「重新部署」(Deploy)。"
else
  echo "正在尝试通知 Fcitx5 重新部署..."
  fcitx5-remote -r && echo "Fcitx5 已触发重新部署。" || echo "请手动重启 Fcitx5 或执行重新部署。"
fi
echo "------------------------------------------------"
