global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  evaluation_interval: ${PROMETHEUS_EVALUATION_INTERVAL}
  external_labels:
    monitored_host: ${MONITORED_HOSTNAME}
    monitored_role: central-monitor

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - ${ALERTMANAGER_TARGET}

rule_files:
  - ${PROMETHEUS_RULES_PATH}

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - ${PROMETHEUS_SELF_TARGET}

  - job_name: alertmanager
    static_configs:
      - targets:
          - ${ALERTMANAGER_TARGET}

  - job_name: node_exporter
    file_sd_configs:
      - files:
          - ${NODE_EXPORTERS_FILE_PATH}
    relabel_configs:
      - source_labels: [host_alias]
        regex: (.+)
        target_label: instance
