apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-macos-self
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_LISTEN_ADDRESS}:${PROMETHEUS_PORT}
    isDefault: true
    editable: false
    jsonData:
      timeInterval: ${PROMETHEUS_SCRAPE_INTERVAL}
