apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-macos-self
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_DATASOURCE_URL}
    isDefault: true
    editable: false
    jsonData:
      timeInterval: ${PROMETHEUS_SCRAPE_INTERVAL}
