apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
  labels:
    owner: lihuu
    env: demo
    region: south
    tier: back
spec:
  containers:
    - image: busybox:latest
      name: busy
      imagePullPolicy: IfNotPresent
      env:
        - name: os
          value: "ubuntu"
        - name: debug
          value: "on"
      command:
        - /bin/echo
      args:
        - "${os}, ${debug}"
